collections:
  - name: kubernetes.core
    version: ">=3.2.0"
  - name: community.docker
    version: ">=2.11.0"
  - name: community.general
    version: ">=9.2.0"
  - name: community.crypto
    version: ">=2.21.1"
  - name: ansible.posix
    version: ">=1.5.4"
