---
- name: TOOLS | Install helm (rhel)
  ansible.builtin.include_tasks: helm_rhel.yml
  when: ansible_os_family == "RedHat"

- name: TOOLS | Install the helm diff plugin
  ansible.builtin.command: helm plugin install https://github.com/databus23/helm-diff
  register: helm_plugin_install
  changed_when:
    - helm_plugin_install.rc == 0
    - '"Installed plugin: diff" in helm_plugin_install.stdout'
  failed_when:
    - helm_plugin_install.rc not in [0, 1]
    - '"Error: plugin already exists" not in helm_plugin_install.stdout'
